### ISSUE TITLE
send-c53.order.js ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by jpbuttet** [node-ebics/node-ebics-client#38]
Hello,

Thank you for your interesting work !

I'm trying to download c53 from Credit-Suisse. 
Letter and and keys are okay and my account has been activated by the bank.
I use sen-c53-order.js
Sometimes i can download some data but the next time I get an ERR_INVALID_ARG_TYPE error.
See screenshot.

Any hints ?

Best regards.
JP Buttet

![Capture](https://user-images.githubusercontent.com/7593186/83361901-46b1e000-a38d-11ea-9b7f-1b33af2a8e21.JPG)

**Comment by jpbuttet** [comment]
on other debug console screenshot for the same error shows:
businessCodeShortText:"No data are available at present for the selected download order type"

this error shows up even if some data is available on the bank server (Credi-Suisse).

Could you please help me in solving this issue ?

Best regards.

Jean-Pierre Buttet

![Capture](https://user-images.githubusercontent.com/7593186/83407999-2aa45200-a412-11ea-83ca-56a72ba0321e.JPG)

**Comment by jpbuttet** [comment]
after a double check, I could see that start and end dates that i used were wrong. Now it works with the correct dates.

Thanks

**Comment by Longchuck** [comment]
@jpbuttet can you show me the correct dates you used?
