### ISSUE TITLE
Incorrect signature length (257 vs 256)

### ISSUE THREAD

**Issue by Herrie82** [node-ebics/node-ebics-client#47]
I have a bit of a weird edge case with a payment file where the signature length somehow gets 257 bytes instead of 256 bytes. I'm trying to debug it, but not really sure where the actual issue is yet. If anyone would be able to help with this that would be great!

**Comment by Herrie82** [comment]
@nanov ^

**Comment by Herrie82** [comment]
I was able to track it down a bit further to:

https://github.com/node-ebics/node-ebics-client/blob/master/lib/crypto/Crypto.js#L75

The hex value (if I do "toString('hex')") here will end up being 514 bytes instead of 512 bytes where the first 2 bytes are "00". 

I've now added a nasty workaround by checking for "00" as first 2 bytes and substring it, so it becomes 512 bytes (stripping off the leading "00" and then convert it to base64 again. But I'd like to understand why it gets wrong in the first place.

When I process the same file multiple times, it doesn't happen on every occasion. It seems to be 1 out of 2/3 times.

**Comment by Herrie82** [comment]
My nasty workaround: 

https://github.com/Herrie82/node-ebics-client/commit/d10a3576375a350c01425cf39dda33db405c8a76

**Comment by Herrie82** [comment]
I can confirm that the bank was happy with the new signature after this workaround. I'm still not sure what's the root cause of the 514 bytes with leading 00 though, would be good to tackle that :)

**Comment by Herrie82** [comment]
I've PR-ed a workaround for now: https://github.com/node-ebics/node-ebics-client/pull/50

**Comment by nanov** [comment]
PR is merged and landed in 0.2.1 - thank you very much!
