### ISSUE TITLE
how to transfer with XG1

### ISSUE THREAD

**Issue by dalmif** [node-ebics/node-ebics-client#54]
hi,
i am working on a application that the app should Settle workers' wages every night,
i use EBICS and want to use XG1 order but not found any sample file for `mytestfile.xml` in send-xg1-order.js.
I apologize for my bad English
thanks.

**Comment by Herrie82** [comment]
> i am working on a application that the app should Settle workers' wages every night,
@dalmif Which bank are you using and in which country? Any SEPA XML file (CGI format) should probably work. It really depends a bit on what the bank is expecting in terms of format and layout of the file.

**Comment by dalmif** [comment]
@Herrie82 thanks for answer.
the bank is UBS on Switzerland. ([this](https://www.ubs.com/de/en.html))
i attached the available orders list.
i think i should use Credit Transfer.
 when i use XG1 or XE2 and etc... the response of bank is [EBICS_OK] but not any transaction is done.
<img width="793" alt="Screen Shot 1400-01-10 at 02 54 08" src="https://user-images.githubusercontent.com/17965069/112908082-1c8f9280-9104-11eb-87a3-d6b2c047e8d0.png">

**Comment by Herrie82** [comment]
@dalmif Yes it seems you need either XE2 (which seems to be a Swiss specific format) or XG1 (Global CGI format).

So XG1 might be the correct one to use. Do other order types work for you? Did you check if the bank enabled XG1 for you? You can do this with HKD or HTD order type. It should show you the user(s) and their permissions/enabled order types.

I have this for example as part of my HKD response:
```
<Permission AuthorisationLevel="T">
            <OrderTypes>HCA HCS HIA HVE HVS INI PUB RFT SPR **XG1**</OrderTypes>
</Permission>
```
In general the XG1 order itself shouldn't give you much feedback except that it sent the file and the reference retrieved from the bank. To get the actual status of the file submitted you would need to submit a different order type. 

When I look at http://media.topal.ch/Public/Downloads/ISO20022/EBICS/Financial_Institut/UBS/ubs_keyport_connection_parameters.pdf it seems you might need Z01 or ZE1.

Also from that document I don't see XG1 anymore, but only XEA for CGI payments.

**Comment by dalmif** [comment]
@Herrie82 thanks a lot.
my response in HKD order:
`
      <Permission AuthorisationLevel="E">
         <OrderTypes>RFT XE2 XEA XG1</OrderTypes>
      </Permission>
      <Permission AuthorisationLevel="T">
         <OrderTypes>HCA HCS HIA HVE HVS INI PUB SPR</OrderTypes>
      </Permission>
`
and the file that upload for bank is:
`xml
<?xml version='1.0' encoding='utf-8'?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03 pain.001.001.03.xsd">
	<CstmrCdtTrfInitn>
		<GrpHdr>
			<MsgId>msg20210329224925323645259754ee07</MsgId>
			<CreDtTm>2021-03-29T22:49:25.322+00:00</CreDtTm>
			<NbOfTxs>1</NbOfTxs>
			<CtrlSum>2.00</CtrlSum>
			<InitgPty>
				<Nm>Calanthejazz</Nm>
			</InitgPty>
		</GrpHdr>
		<PmtInf>
			<PmtInfId>pmt20210329224925323606259754ee21</PmtInfId>
			<PmtMtd>TRF</PmtMtd>
			<NbOfTxs>1</NbOfTxs>
			<CtrlSum>2.00</CtrlSum>
			<PmtTpInf>
				<SvcLvl>
					<Cd>SEPA</Cd>
				</SvcLvl>
			</PmtTpInf>
			<ReqdExctnDt>2021-03-29</ReqdExctnDt>
			<Dbtr><Nm>Name</Nm>
		</Dbtr>
		<DbtrAcct>
			<Id>
				<IBAN>IBAN</IBAN>
			</Id>
		</DbtrAcct>
		<DbtrAgt>
			<FinInstnId>
				<BIC>BIC</BIC>
		</FinInstnId>
	</DbtrAgt>
	<ChrgBr>SLEV</ChrgBr>
	<CdtTrfTxInf>
		<PmtId>
			<InstrId>pii1020210329524925324606259754f1e9</InstrId>
			<EndToEndId>pete1020212329224925324606259754f3b</EndToEndId>
		</PmtId>
		<Amt>
			<InstdAmt Ccy="CHF">2.00</InstdAmt>
		</Amt>
		<CdtrAgt>
			<FinInstnId>
				<BIC>BIC</BIC>
			</FinInstnId>
		</CdtrAgt>
		<Cdtr>
			<Nm>NAME</Nm>
		</Cdtr>
		<CdtrAcct>
			<Id>
				<IBAN>IBAN</IBAN>
			</Id>
		</CdtrAcct>
		<RmtInf>
			<Ustrd>Test payment  1</Ustrd>
		</RmtInf>
	</CdtTrfTxInf>
</PmtInf>
</CstmrCdtTrfInitn>
</Document>
`
note: the number and IDs has been changed on xml.
but amount for transfer is 2 CHF (Swiss Franc) for test. (Is it possible that the order will not be executed because the amount for transfer is small?)

**Comment by Herrie82** [comment]
The bank should execute it. The best is to check the status with the bank. In case sending XG1 doesn't give any errors, you might want to check the status in Z01/ZE1 order. Though it seems your user doesn't have access to this order type. These Z01/ZE1 should normally give you an XML with processing results.

**Comment by Herrie82** [comment]
@dalmif I have been reworking the code for the samples a bit. I'm waiting for @nanov to review my suggestions. This should make the whole testing a lot more straightforward as well. It still won't solve your issue directly, but it should give a bit more flexibility in terms of testing: https://github.com/node-ebics/node-ebics-client/pull/58

**Comment by dalmif** [comment]
thanks a lot @Herrie82,
i solve my problem with check error contains in Z01 order.
i ordered with XG1 and SEPA but i used CHF for currency.
when i found error on Z01 order, i changed currency to EUR and everything work well.
