### ISSUE TITLE
Support for Custom Order Types

### ISSUE THREAD

**Issue by vsia7** [node-ebics/node-ebics-client#86]
Hi,

Is this possible to use this library with custom order types? I am trying to connect to UBS and download transaction and position statements. They have custom order types like ZAA for forex transaction download.

Thanks

**Comment by nanov** [comment]
You can define your own order type, similar to the format defined in [predefined ones](https://github.com/node-ebics/node-ebics-client/blob/master/lib/predefinedOrders/Z53.js) and then use it, as in [this example](https://github.com/node-ebics/node-ebics-client/blob/master/examples/send-c52-order-zipped.js#L11).
