### ISSUE TITLE
Different licenses - LICENSE (MIT) vs package.json (GPL-3.0-only)

### ISSUE THREAD

**Issue by frudolf** [node-ebics/node-ebics-client#91]
It seems that the update of the package.json was overlooked when updating the LICENSE (https://github.com/node-ebics/node-ebics-client/commit/7520a56be8ba446d3466c6dc9202b1d65ea3396f). The [package.json](https://github.com/node-ebics/node-ebics-client/blob/master/package.json#L60) still contains the old GPL-3.0-only license which has already been updated in the LICENSE file. If I understand correctly, it should be just a matter of updating the package.json to MIT, correct?

**Comment by nanov** [comment]
Addressed in 4.1.0
